name: Deploy Azure Function with IaC

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_RESOURCE_GROUP: zzp2025
  AZURE_LOCATION: westeurope

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Check if resource group exists
        id: check-rg
        continue-on-error: true
        run: |
          exists=$(az group exists --name ${{ env.AZURE_RESOURCE_GROUP }})
          echo "::set-output name=exists::$exists"

      - name: Create resource group if it doesn't exist
        if: steps.check-rg.outputs.exists == 'false'
        run: |
          az group create --name ${{ env.AZURE_RESOURCE_GROUP }} --location ${{ env.AZURE_LOCATION }}

      - name: Deploy Bicep template
        id: deploy-bicep
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
          template: ./infra/main.bicep
          parameters: ./infra/parameters.json

      - name: Get function app name
        id: get-function-app-name
        run: |
          functionAppName=$(az deployment group show --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --name ${{ steps.deploy-bicep.outputs.deploymentName }} --query properties.outputs.functionAppName.value -o tsv)
          echo "::set-output name=functionAppName::$functionAppName"

      - name: Package function app
        run: |
          zip -r function.zip ./src/*

      - name: Deploy function code
        run: |
          az functionapp deployment source config-zip \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --name ${{ steps.get-function-app-name.outputs.functionAppName }} \
            --src ./function.zip

      - name: Logout from Azure
        if: always()
        run: |
          az logout
