name: Update Function Code

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AZURE_RESOURCE_GROUP: zzp2025

jobs:
  deploy-function-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Get function app name
        id: get-function-app-name
        run: |
          functionAppName=$(az functionapp list --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --query "[0].name" -o tsv)
          echo "::set-output name=functionAppName::$functionAppName"

      - name: Package function app
        run: |
          zip -r function.zip ./src/*

      - name: Deploy function code
        run: |
          az functionapp deployment source config-zip \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --name ${{ steps.get-function-app-name.outputs.functionAppName }} \
            --src ./function.zip

      - name: Logout from Azure
        if: always()
        run: |
          az logout
